### ISSUE TITLE
Support :not pseudo class

### ISSUE THREAD

**Issue by drauch** [atifaziz/Fizzler#70] opened 2020-04-10 09:14 UTC
Idea: support the [:not pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) ([German translation](https://developer.mozilla.org/de/docs/Web/CSS/:not))

Best regards,
D.R.

---
Edited to link English and German documentation of the _negation pseudo-class_.

**Comment by atifaziz** [comment] 2020-04-12 10:39
Closing as duplicate of #33.

**Closed by atifaziz** 2020-04-12 10:39 UTC
Labels: enhancement, help wanted
