### ISSUE TITLE
Bug with selector containing attribute equality

### ISSUE THREAD

**Issue by drauch** [atifaziz/Fizzler#69] opened 2020-04-10 08:42 UTC
On page https://www.zima.at/wohnen/wien/ when I perform the following in my Chrome developer tools:

```
document.querySelectorAll('div.wpb_tab[aria-hidden=\'false\'] .row-inner-wrap').length
```

it returns 2.

When I perform the very same query with Fizzler it doesn't return any nodes. If I remove the attribute equality selector (i.e., `[aria-hidden=\'false\']`) it properly returns elements (although too many, because I don't need the ones with aria-hidden=true).

I guess this is a bug in your library. Hopefully you can fix it, I'd be really glad :-)

Best regards,
D.R.

**Comment by atifaziz** [comment] 2020-04-10 14:15
It looks like the ARIA attributes are added dynamically through JavaScript and do not exist in the HTML source of the web page when it is returned by the server. For example:

    $ curl https://www.zima.at/wohnen/wien/ | grep aria

returns nothing, proving that the source has no ARIA attributes. If you disable JavaScript in Chrome, your selector also returns nothing. So I am afraid, you'll have to find another criteria/selector to select the elements you wish to reach in the HTML document.

I am closing this as it is not a bug in Fizzler but rather an issue of how the page is authored.

**Closed by atifaziz** 2020-04-10 14:16 UTC

**Comment by drauch** [comment] 2020-04-10 15:35
Oh boy, sorry for any inconvenience, totally missed that.
